{% set versions = {
    "1.6.27": "87e64d1a3df7148c20e1f382c9f189ad428cdaf0c3425efa25c2e1b5ba003ad7"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "applgrid")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace('/', '.')|replace('-', '.') }}

source:
  url: "https://applgrid.hepforge.org/downloads/applgrid-{{ version }}.tgz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  patches:
    - patches/cstdint.patch

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler
    
    - cmake                        # Build system
    - make                         # Make utility

  host:
    - hoppet
    - root
    - lhapdf>=6

  run:
    - hoppet
    - root
    - lhapdf>=6

about:
  home: "https://applgrid.hepforge.org"
  license: "GPL-3.0"
  summary: "The APPLgrid project provides a fast and flexible way to reproduce the results of full NLO calculations"
  description: |
    The APPLgrid project provides a fast and flexible way to reproduce the results of full NLO calculations with any input parton distribution set in only a few milliseconds rather than the weeks normally required to gain adequate statistics.
    Written in C++ (although a fortran interface is included) it can be used for the calculation of any process where the hard subprocess weights from the convolution with the PDF are available from the calculation.

extra:
  recipe-maintainers:
    - meiyasan
